# Spyre accelerator build configuration
# BASE_IMAGE: the Spyre base image from quay.io/aipcc/base-images
BASE_IMAGE=quay.io/aipcc/base-images/spyre-el9.8:3.6.0-ea.2
PYLOCK_FLAVOR=spyre
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-pytorch-spyre-py312
PRODUCT=odh
RELEASE=3.6
