---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/blob/main/jupyter/pytorch/spyre-python-3.12"
    opendatahub.io/notebook-image-name: "Jupyter | PyTorch | Spyre | Python 3.12"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with PyTorch libraries and Spyre accelerator support to start experimenting with advanced AI/ML notebooks on IBM Spyre hardware."
    opendatahub.io/notebook-image-order: "14"
    opendatahub.io/recommended-accelerators: '["spyre"]'
  name: jupyter-pytorch-spyre-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Spyre", "version": "latest"},
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.x"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab", "version": "4.x"},
            {"name": "PyTorch", "version": "2.x"},
            {"name": "Numpy", "version": "2.x"},
            {"name": "Pandas", "version": "2.x"},
            {"name": "Scikit-learn", "version": "1.x"},
            {"name": "Scipy", "version": "1.x"},
            {"name": "Odh-Elyra", "version": "5.x"},
            {"name": "Matplotlib", "version": "3.x"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-workbench-jupyter-pytorch-spyre-py312
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-pytorch-spyre-py312-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-pytorch-spyre-py312-n_PLACEHOLDER
      name: "3.6"
      referencePolicy:
        type: Source
    # N - 1 Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Spyre", "version": "latest"},
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.x"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab", "version": "4.x"},
            {"name": "PyTorch", "version": "2.x"},
            {"name": "Numpy", "version": "2.x"},
            {"name": "Pandas", "version": "2.x"},
            {"name": "Scikit-learn", "version": "1.x"},
            {"name": "Scipy", "version": "1.x"},
            {"name": "Odh-Elyra", "version": "5.x"},
            {"name": "Matplotlib", "version": "3.x"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-workbench-jupyter-pytorch-spyre-py312
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-pytorch-spyre-py312-commit-3-5_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-pytorch-spyre-py312-3-5_PLACEHOLDER
      name: "3.5"
      referencePolicy:
        type: Source
